# Generated by Django 5.2.17 on 2026-10-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакт')),
                ('request', models.TextField(max_length=5000, verbose_name='Запрос')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('telegram_bot', 'Telegram')], default='manual', max_length=20, verbose_name='Источник')),
                ('submission_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='leads', to='crm.tag')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
