import { test, expect } from '@playwright/test';

test('manager creates a lead, tags it, filters, removes tag and logs out', async ({ page }) => {
  const unique = Date.now().toString();
  await page.goto('/');
  await page.getByLabel('Логин').fill(process.env['E2E_USERNAME'] || 'e2e-manager');
  await page.getByLabel('Пароль').fill(process.env['E2E_PASSWORD'] || 'Local-e2e-pass-123');
  await page.getByRole('button', { name: 'Войти', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Заявки' })).toBeVisible();
  await page.getByRole('button', { name: 'Добавить лид' }).click();
  await page.getByLabel('Имя').fill('Тест ' + unique);
  await page.getByLabel('Контакт').fill('@test' + unique);
  await page.getByLabel('Запрос').fill('Нужна CRM');
  await page.getByRole('button', { name: 'Сохранить лид' }).click();
  const row = page.getByRole('row').filter({ hasText: 'Тест ' + unique });
  await expect(row).toBeVisible();
  await page.getByRole('button', { name: 'Создать тег' }).click();
  await page.getByLabel('Название тега').fill('Тег ' + unique);
  await page.getByRole('button', { name: 'Сохранить тег' }).click();
  await row.getByRole('button', { name: 'Назначить теги' }).click();
  await page.getByLabel('Тег ' + unique, { exact: true }).check();
  await page.getByRole('button', { name: 'Сохранить теги' }).click();
  await expect(row).toContainText('Тег ' + unique);
  await page.getByRole('button', { name: 'Тег ' + unique, exact: true }).click();
  await expect(row).toBeVisible();
  await row.getByRole('button', { name: 'Назначить теги' }).click();
  await page.getByLabel('Тег ' + unique, { exact: true }).uncheck();
  await page.getByRole('button', { name: 'Сохранить теги' }).click();
  await expect(page.getByRole('heading', { name: 'Нет заявок с этим тегом' })).toBeVisible();
  await page.getByRole('button', { name: 'Все заявки', exact: true }).click();
  await expect(row).toBeVisible();
  await page.screenshot({ path: '../preview-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '../preview-mobile.png', fullPage: true });
  await expect(page.getByRole('button', { name: 'Добавить лид' })).toBeVisible();
  await page.setViewportSize({ width: 1280, height: 800 });
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Заявки' })).toBeVisible();
  await page.getByRole('button', { name: 'Выйти' }).click();
  await expect(page.getByLabel('Логин')).toBeVisible();
});
